version: "3"

services:
  workbench:
    container_name: rstudio-workbench
    image: rstudio/rstudio-workbench:${RSW_VERSION:-ubuntu2204}
    environment:
      RSW_LICENSE: ${RSW_LICENSE}
      LICENSE_SERVER: ${RSW_LICENSE_SERVER}
    ports:
      - "127.0.0.1:8787:8787"
      - "127.0.0.1:5559:5559"
    volumes:
      - /path/to/secret:/run/secrets

  package-manager:
    container_name: rstudio-package-manager
    image: rstudio/rstudio-package-manager:${RSPM_VERSION:-ubuntu2204}
    environment:
      RSPM_LICENSE: ${RSPM_LICENSE}
      LICENSE_SERVER: ${RSPM_LICENSE_SERVER}
    ports:
      - "127.0.0.1:4242:4242"
